### ISSUE TITLE
Unable to compile with Intel icpc 19.1.3.304 (Intel ComposerXE 2020u4) - Intel intrinsic functions

### ISSUE THREAD

**Issue by prehensilecode** [bbuchfink/diamond#587]
- OS: RHEL 8.1
- Compiler: icpc 19.1.3.304 (from Intel ComposerXE 2020u4)
- NCBI Blast: 2.11.0
- CMake: 3.23.1

Compiler errors on intrinsic function names:
```
/ifs/opt/src/diamond/src/dp/swipe/../../basic/../basic/../util/simd.h(73): error: the global scope has no "_mm_set1_epi8"
    return ::_mm_set1_epi8(v);

/ifs/opt/src/diamond/src/dp/swipe/../../basic/../basic/../util/simd.h(81): error: the global scope has no "_mm_set1_epi16"
    return ::_mm_set1_epi16(v);

/ifs/opt/src/diamond/src/dp/swipe/../../basic/../basic/../util/simd.h(101): error: the global scope has no "_mm256_set1_epi16"
    return ::_mm256_set1_epi16(v);
```

Also, a warning about an unimplemented (GCC) pragma:
```
/ifs/opt/src/diamond/src/dp/swipe/../../basic/../basic/../util/simd.h(131): warning #1879: unimplemented pragma ignored
  #pragma GCC target("arch=x86-64")
```
